version: '3.9'

services:
  flask-api:
    build:
      context: .
      dockerfile: docker/flask.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./task_manager:/app
      
  workspace:
    build:
      context: .
      dockerfile: docker/workspace.Dockerfile
    ports:
      - "8000:8000"
    working_dir: /workspace
  
  nginx-preview:
    build:
      context: .
      dockerfile: docker/nginx_preview.Dockerfile
    volumes:
      - ./preview:/usr/share/nginx/html
    ports:
      - "8080:80"